### ISSUE TITLE
id in DeleteServerParams should be i32

### ISSUE THREAD

**Issue by kpcyrd** [HenningHolmDE/hcloud-rust#9]
hi!

Reading the documentation of [`DeleteServerParams`](https://docs.rs/hcloud/0.6.0/hcloud/apis/servers_api/struct.DeleteServerParams.html) it sounds like this is the i32 id field in the [`Server`](https://docs.rs/hcloud/0.6.0/hcloud/models/server/struct.Server.html) struct, but since the type is String I went with the server name and this didn't work. Converting the i32 id field to a string did work though. This field should probably be a i32 instead (I didn't check the other structs, this is just the one I ran into).

Thanks!

**Comment by HenningHolmDE** [comment]
Thanks for reporting the issue, @kpcyrd !

Taking a quick look into the current API description, Hetzner seems to have changed the type from `string` to `integer` since the latest release of `hcloud-rust` - a change that of course makes total sense.

There will probably be a new release based on the current state of the API at the end of the week that should fix this issue together with everything else that has changed meanwhile.

**Comment by HenningHolmDE** [comment]
Actually I had the same issue in the `create_delete_server` example and also used `server_info.id.to_string()` when instantiating `DeleteServerParams`. It didn't bother me back then but of course the string type does not make any sense here. Thanks again for pointing this out, @kpcyrd !

As Hetzner had in fact corrected the type in their API description during the last few weeks, I only had to update the generated code for this to work.

I just published the new release 0.7.0 with the updated code that should fix the issue.
